[project]
name = "dashboard-internal"
version = "0.1.0"
description = "Dashboard internal untuk reporting data"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["streamlit>=1.45.1", "pandas>=2.0.0", "numpy>=1.24.0"]

[project.scripts]
# dashboard = "streamlit run app.py"

[build-system]
requires = ["setuptools>=64", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/dashboard/_version.py"
version_scheme = "guess-next-dev"
local_scheme = "no-local-version"
fallback_version = "0.1.0"

[dependency-groups]
dev = [
    "mypy>=1.16.0",
    "pre-commit>=4.2.0",
    "pytest>=8.4.0",
    "pytest-cov>=6.1.1",
    "pytest-html>=4.1.1",
    "pytest-mock>=3.14.1",
    "ruff>=0.11.12",
]
# Ruff Linting and Formatting Configuration
[tool.ruff]
target-version = "py312"
line-length = 88
indent-width = 4
respect-gitignore = true
extend-exclude = [
    "__pycache__",
    ".git",
    ".venv",
    "venv",
    "build",
    "dist",
    "*.egg-info",
    ".pytest_cache",
    ".ruff_cache",
    "src/dashboard/_version.py", # Generated file only
]

[tool.ruff.lint]
fixable = ["ALL"]
unfixable = []
select = [
    "F",     # Pyflakes (error detection)
    "E",     # pycodestyle errors
    "W",     # pycodestyle warnings
    "I",     # isort (import sorting)
    "B",     # flake8-bugbear (common bugs + security)
    "C",     # flake8-comprehensions
    "Q",     # flake8-quotes
    "UP",    # pyupgrade (modern Python security)
    "S",     # flake8-bandit (security) ✅ Enhanced
    "N",     # pep8-naming
    "RUF",   # ruff-specific rules
    "D",     # pydocstyle
    "ASYNC", # Async security issues
    "LOG",   # Logging security
    "PTH",   # Path traversal security
    "ARG",   # Argument validation
    "PLR",   # Pylint rules
    "T",     # Type checking
]
ignore = [
    "E501",    # Line too long (handled by formatter)
    "S101",    # Use of assert (needed in tests)
    "B008",    # Function calls in argument defaults
    "D100",    # Missing docstring in public module
    "D101",    # Missing docstring in public class
    "D102",    # Missing docstring in public method
    "D103",    # Missing docstring in public function
    "D104",    # Missing docstring in public package
    "D105",    # Missing docstring in magic method
    "D107",    # Missing docstring in __init__
    "D401",    # First line should be in imperative mood
    "D203",    # 1 blank line required before class docstring (conflicts with D211)
    "D213",    # Multi-line docstring summary should start at the second line (conflicts with D212)
    "N803",    # Argument name should be lowercase
    "N806",    # Variable in function should be lowercase
    "S603",    # subprocess-shell-use
    "T201",    # print() statements (allow in scripts)
    "PLR2004", # Magic value used in comparison
    "S101",    # assert (OK in tests)
    "S603",    # subprocess (controlled usage for GSM)
    "S607",    # partial executable path (OK for automation)
    "S108",    # hardcoded temp file (OK in controlled env)
]
[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = [
    "Q000",    # Allow single quotes in tests
    "S101",    # Assert usage OK in tests
    "D",       # Docstrings not required in all test functions
    "UP038",   # Consistent tuple syntax in tests
    "S106",    # Hardcoded password OK in test fixtures
    "PLR6301", # Method could be a function (OK in test classes)
    "PLR2004", # Magic values in tests (OK for test data)
    "ARG001",  # Unused function arguments (fixtures)
    "ARG002",  # Unused method arguments (test methods)
    "PLR0913", # Too many arguments (OK for test setup)
    "PLR0915", # Too many statements (OK for complex test scenarios)
    "C901",    # Too complex (OK for comprehensive tests)
    "T201",    # Print statements (OK for debugging tests)
    "B008",    # Function calls in defaults (OK for test fixtures)
]
"scripts/**/*.py" = [
    "T201",    # print() statements OK in scripts
    "D",       # Docstrings not required in scripts
    "ARG001",  # Unused function arguments (fixtures)
    "PLR2004", # Magic values in tests
    "S603",    # subprocess for build scripts
    "S607",    # partial paths for tools
]
"src/dashboard/_version.py" = ["ALL"]
[tool.ruff.lint.pydocstyle]
convention = "google"
ignore-decorators = ["typing.overload"]

[tool.ruff.lint.flake8-quotes]
inline-quotes = "double"
multiline-quotes = "double"
docstring-quotes = "double"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "lf"
docstring-code-format = true
docstring-code-line-length = "dynamic"

[tool.ruff.lint.isort]
known-first-party = ["dashboard"]
section-order = [
    "future",
    "standard-library",
    "third-party",
    "first-party",
    "local-folder",
]
split-on-trailing-comma = true
force-sort-within-sections = true

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.ruff.lint.pylint]
max-args = 8
max-branches = 15
max-returns = 8
max-statements = 60

# Coverage Configuration
[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "if __name__ == .__main__.:",
    "raise NotImplementedError",
    "if TYPE_CHECKING:",
]
show_missing = true
skip_covered = false
skip_empty = true

[tool.coverage.html]
directory = ".reports/coverage/html"
skip_covered = false
skip_empty = true
[tool.coverage.run]
source = ["src"]
data_file = ".reports/coverage/.coverage"
branch = true
parallel = true
include = ["*/dashboard/*"]
exclude = [
    "*/tests/*",
    "*/_version.py",
    "*/scripts/*",
    # "*/__main__.py",
    "*/site-packages/*",
    "*/.venv/*",
    "*/shibokensupport/*",
    "*/pyscript/*",
    "*/signature_bootstrap.py",
]
# Testing Configuration
[tool.pytest.ini_options]
testpaths = ["tests", "src"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"

timeout = 300
timeout_method = "thread"

# ✅ Doctest configuration
doctest_optionflags = [
    "NORMALIZE_WHITESPACE",
    "IGNORE_EXCEPTION_DETAIL",
    "ALLOW_UNICODE",
    "ALLOW_BYTES",
]

addopts = [
    "--strict-markers",
    "--strict-config",
    "--cov=src/dashboard",
    "--cov-report=term",
    "--cov-report=term-missing",
    "--cov-report=html:.reports/coverage/html",
    "--cov-report=xml:.reports/coverage/coverage.xml",
    "--cov-fail-under=80",
    "--cov-config=pyproject.toml",
    "--html=.reports/tests/report.html",
    "--self-contained-html",
    "--doctest-modules",
    "--tb=short",
    "-ra",
    "--showlocals",
    "-v",
]

# Logging Configuration
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)8s] %(name)s: %(message)s"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
log_auto_indent = true

# ✅ Basic markers
markers = [
    "unit: Fast unit tests",
    "integration: Integration tests",
    "web: Web automation tests (requires browser)",
    "slow: Slow tests (> 5 seconds)",
    "network: Tests requiring network access",
    "database: Tests requiring database",
    "hardware: Tests requiring physical hardware",
    "smoke: Smoke tests for quick validation",
    "regression: Regression tests",
]

# ✅ Enhanced warning filters
filterwarnings = []

# ✅ Minimum version requirements
minversion = "8.0"
